project_id = "gwdoxbdblbkgkuhronqo"

[functions.recommendations]
verify_jwt = false

[functions.personalized-recommendations]
verify_jwt = true

[functions.demand-forecast]
verify_jwt = false

[functions.calculate-user-similarity]
verify_jwt = false

[functions.seed-mock-data]
verify_jwt = false

[functions.wallet-topup]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false